"""flag for tweeting

Revision ID: 2609d618a84b
Revises: 92d3e89a251
Create Date: 2013-10-07 02:41:59.863000

"""

# revision identifiers, used by Alembic.
revision = '2609d618a84b'
down_revision = '92d3e89a251'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('polls', sa.Column('announce_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('announce_enabled', sa.Boolean(), nullable=True))

    #no accidents by autotweeting existing polls
    op.execute("UPDATE polls SET announce_enabled = False")
    op.execute("UPDATE users SET announce_enabled = True")

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'announce_enabled')
    op.drop_column('polls', 'announce_enabled')
    ### end Alembic commands ###
