"""poll user relationship

Revision ID: 266a96ae00bb
Revises: c59720036a9
Create Date: 2013-04-01 08:47:23.972000

"""

# revision identifiers, used by Alembic.
revision = '266a96ae00bb'
down_revision = 'c59720036a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'polls', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
            "polls_user_id_fkey", "polls",
            "users", ["user_id"], ["id"])
            
    op.alter_column(u'polls', u'user_email', existing_type=sa.String(), 
                    name=u'email')
    op.drop_column(u'polls', u'twitter_user')
    
    
    op.add_column(u'visits', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
            "visits_user_id_fkey", "visits",
            "users", ["user_id"], ["id"])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'visits', 'user_id')
    
    
    op.alter_column(u'polls', u'email', existing_type=sa.String(), 
                    name=u'user_email')
    op.add_column(u'polls', sa.Column(u'twitter_user', sa.VARCHAR(), nullable=True))
    op.drop_column(u'polls', 'user_id')
    ### end Alembic commands ###
