"""add poll_tweets

Revision ID: 3344607c54b5
Revises: 57563dbab139
Create Date: 2013-03-15 02:09:30.173000

"""

# revision identifiers, used by Alembic.
revision = '3344607c54b5'
down_revision = '57563dbab139'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll_tweets',
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('tweet_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweets.id'], ),
    sa.PrimaryKeyConstraint('poll_id', 'tweet_id')
    )
    op.drop_column(u'tweets', u'poll_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'tweets', sa.Column(u'poll_id', sa.INTEGER(), nullable=True))
    op.drop_table('poll_tweets')
    ### end Alembic commands ###
