"""add session table

Revision ID: 39dc751adeff
Revises: 59931c4ab451
Create Date: 2013-03-24 21:35:13.348000

"""

# revision identifiers, used by Alembic.
revision = '39dc751adeff'
down_revision = '59931c4ab451'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.expression import text

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('atime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    ### end Alembic commands ###
