"""no storing user secrets

Revision ID: 439d1875bec5
Revises: f652b66c641
Create Date: 2013-04-07 23:12:34.253000

"""

# revision identifiers, used by Alembic.
revision = '439d1875bec5'
down_revision = 'f652b66c641'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', u'oauth_secret')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(u'oauth_secret', sa.VARCHAR(), nullable=True))
    ### end Alembic commands ###
