"""ad tweets for questions and polls

Revision ID: 4bdba79ce5e7
Revises: 2236aaffbe1d
Create Date: 2013-10-06 20:54:57.094000

"""

# revision identifiers, used by Alembic.
revision = '4bdba79ce5e7'
down_revision = '2236aaffbe1d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('polls', sa.Column('absolute_url', sa.String(), nullable=True))
    op.add_column('polls', sa.Column('announcement_tweet_id', sa.BigInteger(), nullable=True))
    op.drop_column('polls', u'results_url_code')
    op.drop_column('polls', u'poll_short_url')
    op.drop_column('polls', u'edit_url_code')
    op.add_column('questions', sa.Column('announcement_tweet_id', sa.BigInteger(), nullable=True))

    op.execute("UPDATE polls SET absolute_url = 'http://www.rechattr.com/' || poll_url_human")

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'announcement_tweet_id')
    op.add_column('polls', sa.Column(u'edit_url_code', sa.VARCHAR(), nullable=True))
    op.add_column('polls', sa.Column(u'poll_short_url', sa.VARCHAR(), nullable=True))
    op.add_column('polls', sa.Column(u'results_url_code', sa.VARCHAR(), nullable=True))
    op.drop_column('polls', 'announcement_tweet_id')
    op.drop_column('polls', 'absolute_url')
    ### end Alembic commands ###
