"""update twitter term handling

Revision ID: 4f4f0ed0854
Revises: 175747a10ed
Create Date: 2013-03-14 21:19:19.619000

"""

# revision identifiers, used by Alembic.
revision = '4f4f0ed0854'
down_revision = '175747a10ed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('polls', sa.Column('twitter_hashtag', sa.String(), nullable=True))
    op.add_column('polls', sa.Column('twitter_user', sa.String(), nullable=True))
    op.add_column('polls', sa.Column('twitter_other_terms', sa.String(), nullable=True))
    op.drop_column('polls', u'twitter_terms')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('polls', sa.Column(u'twitter_terms', sa.VARCHAR(), nullable=True))
    op.drop_column('polls', 'twitter_other_terms')
    op.drop_column('polls', 'twitter_user')
    op.drop_column('polls', 'twitter_hashtag')
    ### end Alembic commands ###
