"""integer response type

Revision ID: 5307baf4e54c
Revises: 211559e302c7
Create Date: 2013-10-02 17:51:15.942000

"""

# revision identifiers, used by Alembic.
revision = '5307baf4e54c'
down_revision = '211559e302c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('polls', u'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('polls', u'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
