"""user profile url

Revision ID: 55a399247346
Revises: 2eefd1d21fe9
Create Date: 2013-03-30 15:06:26.076000

"""

# revision identifiers, used by Alembic.
revision = '55a399247346'
down_revision = '2eefd1d21fe9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import scoped_session, sessionmaker
import cPickle as pickle
from model import User

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image_url', sa.String(), nullable=True))
    
    # go through all users and extract the column from the cache
    connection = op.get_bind()
    if connection is None:
        print "profile_image_url added but not updated.";
    else:
        orm = scoped_session(sessionmaker(bind=connection))
        for user in orm.query(User):
            cache = user.load_cache()
            user.profile_image_url = cache.profile_image_url_https

        orm.commit()
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image_url')
    ### end Alembic commands ###
