"""user profile url

Revision ID: 55a399247346
Revises: 2eefd1d21fe9
Create Date: 2013-03-30 15:06:26.076000

"""

# revision identifiers, used by Alembic.
revision = '55a399247346'
down_revision = '2eefd1d21fe9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image_url', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image_url')
    ### end Alembic commands ###
