"""add poll title

Revision ID: 57563dbab139
Revises: 4f4f0ed0854
Create Date: 2013-03-14 21:46:59.264000

"""

# revision identifiers, used by Alembic.
revision = '57563dbab139'
down_revision = '4f4f0ed0854'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('polls', sa.Column('title', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('polls', 'title')
    ### end Alembic commands ###
