"""Create questions table

Revision ID: 5a67bf5f6af4
Revises: 55a399247346
Create Date: 2013-04-01 08:15:13.725000

"""

# revision identifiers, used by Alembic.
revision = '5a67bf5f6af4'
down_revision = '55a399247346'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.Column('trigger_type', sa.String(), nullable=True),
    sa.Column('trigger_info', sa.String(), nullable=True),
    sa.Column('image_src', sa.String(), nullable=True),
    sa.Column('question_text', sa.String(), nullable=True),
    sa.Column('answer_choices', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    ### end Alembic commands ###
