"""olson timezone in user

Revision ID: 7644a90af11
Revises: 939aa06ed8e
Create Date: 2013-04-04 11:10:40.251000

"""

# revision identifiers, used by Alembic.
revision = '7644a90af11'
down_revision = '939aa06ed8e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('olson_timezone', sa.String(), nullable=True))
    op.alter_column('users', u'time_zone',  existing_type=sa.String(), 
                    name='human_timezone')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', u'human_timezone',  existing_type=sa.String(), 
                    name='time_zone')
    op.drop_column('users', 'olson_timezone')
    ### end Alembic commands ###
