"""user oauth secret

Revision ID: 92d3e89a251
Revises: 4bdba79ce5e7
Create Date: 2013-10-06 21:09:28.260000

"""

# revision identifiers, used by Alembic.
revision = '92d3e89a251'
down_revision = '4bdba79ce5e7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_secret', sa.String(), nullable=True))
    op.add_column('users', sa.Column('force_signout', sa.Boolean(), nullable=True))
    ### end Alembic commands ###

    # apply a default to force sign out
    op.execute('UPDATE users SET force_signout = TRUE')

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'force_signout')
    op.drop_column('users', 'oauth_secret')
    ### end Alembic commands ###
