"""question subject field

Revision ID: 939aa06ed8e
Revises: 55a95d175cb3
Create Date: 2013-04-02 17:20:33.334000

"""

# revision identifiers, used by Alembic.
revision = '939aa06ed8e'
down_revision = '55a95d175cb3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('subject', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'subject')
    ### end Alembic commands ###
